### ISSUE TITLE
NoteDensityVariabilityFeature problems due to windowing errors

### ISSUE THREAD

**Issue by codaich** [DDMAL/jSymbolic2#39]
Some (a small minority) files produce in IndexOutOfBoundsExceptions during feature extraction due to windowing problems during NoteDensityVariabilityFeature extraction. This happens even when windowed extraction isn't set to be performed (since NoteDensityVariabilityFeature uses windows internally). Occurs with the attached files: [ProblemFiles.zip](https://github.com/DDMAL/jSymbolic2/files/694869/ProblemFiles.zip).

Please address this as a priority (it may also help debug windowing issues in general). Also, please use my latest jSymbolic2 commit when testing: [10ff92c]. If you do, you will see this kind of problem with the problematic files mentioned above:

jsymbolic2.processing.MIDIIntermediateRepresentations.generatePitchedInstrumentIntermediateRepresentations(MIDIIntermediateRepresentations.java:859)
at jsymbolic2.processing.MIDIIntermediateRepresentations.<init>(MIDIIntermediateRepresentations.java:436)
at jsymbolic2.features.NoteDensityVariabilityFeature.extractFeature(NoteDensityVariabilityFeature.java:79)

You can temporarily uncomment the printStackTrace in the FeatureExtractionJobProcessor.extractFeatures method during debugging if this helps.

**Comment by codaich** [comment]
Fixed in commit [dd8af87], well done. Issued closed.
